apiVersion: v1
kind: Pod
metadata: 
  name: mytestpod
spec:
  containers:
     - name: c0
       image: centos
       command: ["/bin/bash","-c","while do;echo aadi;sleep 4;done"]
       ports:
         - containerPort: 80
  
